"""add_project_key_and_url

Revision ID: 2721ed81737f
Revises: c5d6e7f8a9b0
Create Date: 2026-04-17 10:04:39.762804+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2721ed81737f'
down_revision: Union[str, None] = 'c5d6e7f8a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_key', sa.String(length=50), nullable=True))
    
    # Update existing rows with placeholder
    op.execute("UPDATE projects SET project_key = UPPER(SUBSTRING(name, 1, 3)) WHERE project_key IS NULL")
    op.execute("UPDATE projects SET project_key = 'PRJ' WHERE project_key IS NULL OR project_key = ''")
    
    op.alter_column('projects', 'project_key', nullable=False)
    op.add_column('projects', sa.Column('project_url', sa.String(length=1024), nullable=True))
    op.create_index(op.f('ix_projects_project_key'), 'projects', ['project_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_project_key'), table_name='projects')
    op.drop_column('projects', 'project_url')
    op.drop_column('projects', 'project_key')
    # ### end Alembic commands ###
