"""
Pydantic schemas for validating LLM-generated outputs.

These schemas ensure that LLM-generated JSON for test cases and test data
conforms to the expected structure before being inserted into the database.
"""
from pydantic import BaseModel, Field, field_validator, RootModel
from typing import List, Any


class LLMTestCaseItem(BaseModel):
    """Schema for a single test case generated by LLM."""
    test_case_id: str = Field(..., min_length=1, description="Unique test case identifier")
    module: str = Field(..., min_length=1, description="Module or feature being tested")
    description: str = Field(..., min_length=1, description="What this test validates")
    pre_conditions: str = Field(default="N/A", description="State before test execution")
    steps_to_execute: str = Field(..., min_length=1, description="Test execution steps")
    expected_result: str = Field(..., min_length=1, description="Expected system behavior")

    @field_validator("test_case_id")
    @classmethod
    def validate_test_case_id(cls, v: str) -> str:
        """Ensure test_case_id is not empty and doesn't contain malicious content."""
        if not v or not v.strip():
            raise ValueError("test_case_id cannot be empty")
        # Basic sanitization: prevent extremely long IDs
        if len(v) > 255:
            raise ValueError("test_case_id too long")
        return v.strip()

    @field_validator("module", "description", "steps_to_execute", "expected_result")
    @classmethod
    def validate_non_empty_strings(cls, v: str) -> str:
        """Ensure required string fields are not empty."""
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        # Prevent extremely long values
        if len(v) > 10000:
            raise ValueError("Field value too long")
        return v


class LLMTestCaseResponse(RootModel[List[LLMTestCaseItem]]):
    """Schema for LLM test case generation response (array of test cases)."""
    pass


class LLMTestDataItem(BaseModel):
    """Schema for a single test data item generated by LLM."""
    test_case_id: str = Field(..., min_length=1, description="Associated test case identifier")
    parameter_name: str = Field(..., min_length=1, description="Parameter being tested")
    test_data_value: str = Field(..., min_length=1, description="Test data value")
    data_type: str = Field(..., min_length=1, description="Type of data (string, number, etc.)")

    @field_validator("test_case_id", "parameter_name", "test_data_value", "data_type")
    @classmethod
    def validate_non_empty_strings(cls, v: str) -> str:
        """Ensure required string fields are not empty."""
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        # Prevent extremely long values
        if len(v) > 10000:
            raise ValueError("Field value too long")
        return v.strip()


class LLMTestDataResponse(RootModel[List[LLMTestDataItem]]):
    """Schema for LLM test data generation response (array of test data items)."""
    pass
